#!/usr/bin/env node
'use strict';

import { readFileSync, existsSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';
import { readStdinJson, getCwd, readUnifiedState, writeUnifiedState } from './lib/state.mjs';
import { isPersistentModeActiveFromState, getPersistentModeMessageFromState } from './lib/persistent-mode.mjs';
import { checkCodexResult, formatResultInstruction, isPollWatcherActive } from './lib/codex-result-handler.mjs';
import { getLatestCodexJobStatus } from '../../scripts/lib/codex_bridge.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

const data = readStdinJson();
if (!data) {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

// Honor the payload's project dir (consistent with pre-tool-use / post-tool-use /
// stop-handler / session-start); getCwd() alone ignores its arg and returns
// process.cwd(), which reads/writes .qe state in the wrong dir when the payload
// carries an explicit cwd.
const cwd = data.cwd || data.directory || getCwd(data);
const hints = [];
const COMMAND_PREFIX = process.env.QE_COMMAND_PREFIX || '/';
const skillCommand = (name) => `${COMMAND_PREFIX}${name}`;

// Extract notification info
// Claude Code Notification hook receives: message about agent/subagent completion
const message = data.message || data.notification || '';
const messageStr = typeof message === 'string' ? message : JSON.stringify(message);

// Agent completion chaining — all 16 agents + codex
const chains = [
  { match: 'Etask-executor',     hint: '[CHAIN] Etask-executor completed. Run Earchive-executor in background to archive completed tasks.' },
  { match: 'Erefresh-executor',  hint: 'Analysis updated by Erefresh-executor. Proceed with user\'s request using fresh .qe/analysis/ data.' },
  { match: 'Ecompact-executor',  hint: `Context saved by Ecompact-executor. Safe to continue. Use ${skillCommand('Qresume')} in next session to restore.` },
  { match: 'Earchive-executor',  hint: 'Tasks archived by Earchive-executor. Completed files moved to .qe/.archive/.' },
  { match: 'Ecommit-executor',   hint: 'Commit created by Ecommit-executor. Report commit hash and summary to user.' },
  { match: 'Ecode-debugger',     hint: 'Ecode-debugger completed analysis. Review findings and apply suggested fixes.' },
  { match: 'Ecode-doc-writer',   hint: 'Documentation generated by Ecode-doc-writer. Review output with user.' },
  { match: 'Ecode-reviewer',     hint: 'Code review completed by Ecode-reviewer. Present findings and ask user about fixes.' },
  { match: 'Ecode-test-engineer', hint: 'Tests written by Ecode-test-engineer. Run tests to verify they pass.' },
  { match: 'Edeep-researcher',   hint: 'Research completed by Edeep-researcher. Summarize findings for user.' },
  { match: 'Edoc-generator',     hint: 'Document generated by Edoc-generator. Check output file and report path to user.' },
  { match: 'Egrad-writer',       hint: 'Chapter draft completed by Egrad-writer. Review academic style and citations.' },
  { match: 'Ehandoff-executor',  hint: 'Handoff document generated by Ehandoff-executor. Saved to .qe/handoffs/.' },
  { match: 'Epm-planner',        hint: 'Planning document created by Epm-planner. Review and confirm with user.' },
  { match: 'Eqa-orchestrator',   hint: '[CHAIN] Eqa-orchestrator completed quality loop. Report test/review/fix results to user.' },
  { match: 'codex-rescue',       hint: null, action: 'codex-poll' },
  { match: 'codex-review',       hint: '[CODEX] Codex review completed. Parse review findings and map to supervision verdict.' },
];

let agentChainMatched = false;
let codexPollStarted = false;

for (const { match, hint, action } of chains) {
  const regex = new RegExp(`\\b${match}\\b`);
  if (regex.test(messageStr)) {
    agentChainMatched = true;

    if (action === 'codex-poll') {
      // --- Check immediate result first, then spawn watcher if needed ---
      const signalFile = join(cwd, '.qe', 'agent-results', 'codex-ready.signal');

      // Check if Codex already finished (companion state or prior signal)
      const immediateResult = checkCodexResult(cwd);

      if (immediateResult.status === 'completed') {
        // Codex already done — no need to poll, pass result directly
        try {
          const st = readUnifiedState(cwd);
          st.codex_materialization = { ...immediateResult, checkedAt: new Date().toISOString() };
          writeUnifiedState(cwd, st);
        } catch {}
        hints.push(`[CODEX] ${formatResultInstruction(immediateResult)}`);
        codexPollStarted = true; // skip watcher spawn
      } else if (immediateResult.status === 'failed' || immediateResult.status === 'crashed') {
        try {
          const st = readUnifiedState(cwd);
          st.codex_materialization = { ...immediateResult, checkedAt: new Date().toISOString() };
          writeUnifiedState(cwd, st);
        } catch {}
        hints.push(`[CODEX] ${formatResultInstruction(immediateResult)}`);
        codexPollStarted = true;
      } else {
        // Not yet done — spawn background poll watcher
        try { if (existsSync(signalFile)) unlinkSync(signalFile); } catch {}

        const watcherScript = join(__dirname, 'lib', 'codex-poll-watcher.mjs');
        let companionPid = immediateResult.pid ?? null;
        if (!companionPid) {
          try {
            const latest = getLatestCodexJobStatus(cwd);
            companionPid = latest.found ? latest.pid ?? null : null;
          } catch {}
        }

        try {
          const watcherArgs = [watcherScript, cwd, '--interval', '30', '--timeout', '3600'];
          if (Number.isInteger(companionPid) && companionPid > 0) watcherArgs.push('--pid', String(companionPid));
          const child = spawn('node', watcherArgs, {
            cwd,
            detached: true,
            stdio: 'ignore',
          });
          child.unref();
          codexPollStarted = true;
        } catch {
          codexPollStarted = false;
        }

        // Record pending state so skills know to check back
        try {
          const st = readUnifiedState(cwd);
          st.codex_materialization = {
            status: 'running',
            source: 'poll-watcher',
            startedAt: new Date().toISOString(),
            signalFile,
            pid: Number.isInteger(companionPid) && companionPid > 0 ? companionPid : null,
          };
          writeUnifiedState(cwd, st);
        } catch {}

        if (codexPollStarted) {
          hints.push(`[CODEX] Codex rescue returned Done — materialization pending. A background watcher is polling every 30s (1h timeout). To check status NOW, read the result with these steps:

1. Run: cat ${signalFile} 2>/dev/null || echo "still polling"
   - "detected: true" → files written, proceed to Verify stage
   - "still polling" → companion still working, check again in 30s
   - "timeout: true" → 1h passed, use the interaction adapter for fallback

2. Or check companion directly: import { checkCodexResult } from codex-result-handler.mjs

FALLBACK: If no progress after 2 checks, use the interaction adapter: (a) Retry Codex (b) Implement with Claude (c) Check Codex logs`);
        } else {
          hints.push(`[CODEX] Codex rescue returned Done but poll watcher failed to start. Run \`git diff --stat\` to check for changes. If none, implement with Claude instead.`);
        }
      }
    } else if (hint) {
      hints.push(hint);
    }

    // --- Codex error detection for graceful fallback ---
    if (match === 'codex-rescue' || match === 'codex-review') {
      const errorPatterns = [
        { pattern: /rate.?limit/i, type: 'rate_limit' },
        { pattern: /quota.?exceed/i, type: 'quota_exceeded' },
        { pattern: /timeout|timed?\s*out/i, type: 'timeout' },
        { pattern: /connection.?(?:refused|reset|error)/i, type: 'connection_error' },
        { pattern: /unauthorized|403|401/i, type: 'auth_error' },
      ];
      for (const { pattern, type } of errorPatterns) {
        if (pattern.test(messageStr)) {
          try {
            const errState = readUnifiedState(cwd);
            errState.codex_last_error = { type, timestamp: new Date().toISOString() };
            writeUnifiedState(cwd, errState);
          } catch {}
          hints.push(`[CODEX ERROR] Detected ${type}. Codex will be marked unreachable for 5 minutes. Claude fallback will be allowed for SIVS-codex stages.`);
          break;
        }
      }
    }

    break;  // One chain action per notification
  }
}

// --- Persistent Mode Reinforcement ---
// Skip reinforcement if an agent chain was matched above.
try {
  if (!agentChainMatched) {
    const unifiedState = readUnifiedState(cwd);
    const pm = isPersistentModeActiveFromState(unifiedState);
    if (pm.active) {
      const completionPatterns = /\b(complet|finish|done|wrap|final|conclud|summar|handoff|hand off|result|output ready)\b/i;
      if (completionPatterns.test(messageStr)) {
        const reinforcement = getPersistentModeMessageFromState(unifiedState);
        if (reinforcement) {
          if (unifiedState.persistentMode) {
            unifiedState.persistentMode.reinforcements = (unifiedState.persistentMode.reinforcements || 0) + 1;
            try { writeUnifiedState(cwd, unifiedState); } catch {}
          }
          hints.push(reinforcement);
        }
      }
    }
  }
} catch {
  // Fault tolerance — never let persistent mode crash the notification hook
}

if (hints.length > 0) {
  console.log(JSON.stringify({
    continue: true,
    hookSpecificOutput: {
      hookEventName: "Notification",
      additionalContext: `[QE] ${hints.join(' | ')}`
    }
  }));
} else {
  console.log(JSON.stringify({ continue: true }));
}
