#!/usr/bin/env node
'use strict';

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

let input = '';
try {
  input = readFileSync('/dev/stdin', 'utf8');
} catch {
  process.exit(0);
}

let data;
try {
  data = JSON.parse(input);
} catch {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}

const cwd = data.cwd || data.directory || process.cwd();
const hints = [];

// Extract notification info
// Claude Code Notification hook receives: message about agent/subagent completion
const message = data.message || data.notification || '';
const messageStr = typeof message === 'string' ? message : JSON.stringify(message);

// Agent completion chaining — all 16 agents
const chains = [
  { match: 'Etask-executor',     hint: '[CHAIN] Etask-executor completed. Run Earchive-executor in background to archive completed tasks.' },
  { match: 'Erefresh-executor',  hint: 'Analysis updated by Erefresh-executor. Proceed with user\'s request using fresh .qe/analysis/ data.' },
  { match: 'Ecompact-executor',  hint: 'Context saved by Ecompact-executor. Safe to continue. Use /Qresume in next session to restore.' },
  { match: 'Earchive-executor',  hint: 'Tasks archived by Earchive-executor. Completed files moved to .qe/.archive/.' },
  { match: 'Ecommit-executor',   hint: 'Commit created by Ecommit-executor. Report commit hash and summary to user.' },
  { match: 'Ecode-debugger',     hint: 'Ecode-debugger completed analysis. Review findings and apply suggested fixes.' },
  { match: 'Ecode-doc-writer',   hint: 'Documentation generated by Ecode-doc-writer. Review output with user.' },
  { match: 'Ecode-reviewer',     hint: 'Code review completed by Ecode-reviewer. Present findings and ask user about fixes.' },
  { match: 'Ecode-test-engineer', hint: 'Tests written by Ecode-test-engineer. Run tests to verify they pass.' },
  { match: 'Edeep-researcher',   hint: 'Research completed by Edeep-researcher. Summarize findings for user.' },
  { match: 'Edoc-generator',     hint: 'Document generated by Edoc-generator. Check output file and report path to user.' },
  { match: 'Egrad-writer',       hint: 'Chapter draft completed by Egrad-writer. Review academic style and citations.' },
  { match: 'Ehandoff-executor',  hint: 'Handoff document generated by Ehandoff-executor. Saved to .qe/handoffs/.' },
  { match: 'Epm-planner',        hint: 'Planning document created by Epm-planner. Review and confirm with user.' },
  { match: 'Eprofile-collector',  hint: 'Profile updated by Eprofile-collector. Data saved to .qe/profile/.' },
  { match: 'Eqa-orchestrator',   hint: '[CHAIN] Eqa-orchestrator completed quality loop. Report test/review/fix results to user.' },
];

for (const { match, hint } of chains) {
  if (messageStr.includes(match)) {
    hints.push(hint);
  }
}

if (hints.length > 0) {
  console.log(JSON.stringify({
    continue: true,
    hookSpecificOutput: {
      hookEventName: "Notification",
      additionalContext: `[QE] ${hints.join(' | ')}`
    }
  }));
} else {
  console.log(JSON.stringify({ continue: true }));
}
