#!/usr/bin/env node
/**
 * doc-index.mjs — derived `.qe/index.md` rebuild helper (Phase 3 / G019, G022).
 *
 * `.qe/index.md` is a Map-of-Content (MOC) over the active execution-document
 * directories. It is a DERIVED artifact: every rebuild scans current directory
 * state and writes the whole file. There is no append path — appending is what
 * produced stale rows on lifecycle moves and lost updates under concurrency.
 *
 * A single writer performs a temp+rename so a reader never observes a partially
 * written index. Two sessions racing to rebuild resolve last-rename-wins; the
 * next rebuild re-scans current state and self-heals, and no document file is
 * ever at risk (only the derived index).
 *
 * `.qe/.archive/**` is intentionally excluded: the active MOC must not be
 * polluted by archive accumulation.
 */

import { readdirSync, readFileSync, existsSync, writeFileSync, renameSync } from 'node:fs';
import { join, relative, sep, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractDocFrontmatter } from './doc-frontmatter.mjs';

/** The six execution-document kinds, in index section order. */
export const KINDS = ['spec', 'verify', 'audit', 'execution', 'handoff', 'report'];

/**
 * Active lifecycle directories scanned for the index, relative to `.qe`. The
 * tasks lane is limited to its four lifecycle folders (never `.archive`); the
 * remaining lanes are scanned whole. Any path segment named `.archive` is
 * excluded regardless.
 */
const SCAN_ROOTS = [
  'tasks/pending',
  'tasks/in-progress',
  'tasks/on-hold',
  'tasks/completed',
  'checklists',
  'security-reports',
  'agent-results',
  'handoffs',
];

/** Sharding threshold: only a kind section past this estimated token size shards. */
const SHARD_TOKEN_LIMIT = 50_000;

const GENERATED_MARKER = '<!-- generated by scripts/lib/doc-index.mjs — do not edit by hand -->';

/** Rough token estimate: ~4 chars per token is enough to decide sharding. */
function estimateTokens(text) {
  return Math.ceil(String(text || '').length / 4);
}

/** Infer the document kind from its filename when no frontmatter declares one. */
function inferKindFromName(name) {
  if (name.startsWith('TASK_REQUEST')) return 'spec';
  if (name.startsWith('VERIFY_CHECKLIST')) return 'verify';
  if (name.startsWith('SECURITY_REPORT') || name.startsWith('risk-proof')) return 'audit';
  if (name.startsWith('HANDOFF')) return 'handoff';
  if (name.startsWith('REMEDIATION')) return 'report';
  return 'report';
}

/** Derive the shard key: first hex char of an 8-hex uuid, else `-misc`. */
function shardKey(uuid) {
  return /^[0-9a-f]/.test(String(uuid || '')) && /^[0-9a-f]{8}$/.test(String(uuid || ''))
    ? String(uuid)[0]
    : '-misc';
}

/** Best-effort uuid: frontmatter uuid, else an 8-hex run in the filename, else ''. */
function deriveUuid(metadata, name) {
  if (metadata && typeof metadata.uuid === 'string' && metadata.uuid) return metadata.uuid;
  const hex = name.match(/([0-9a-f]{8})/);
  if (hex) return hex[1];
  return '';
}

/** First H1 line, stripped of the leading `# `, used as the display title. */
function deriveTitle(text) {
  const first = String(text || '').split('\n')[0] || '';
  return /^#\s+/.test(first) ? first.replace(/^#\s+/, '').trim() : '';
}

/** Lifecycle status from frontmatter, else inferred from the containing folder. */
function deriveStatus(metadata, relPath) {
  if (metadata && typeof metadata.status === 'string' && metadata.status) return metadata.status;
  if (relPath.includes('/completed/')) return 'completed';
  if (relPath.includes('/in-progress/')) return 'in-progress';
  if (relPath.includes('/on-hold/')) return 'on-hold';
  if (relPath.includes('/pending/')) return 'pending';
  return '';
}

/**
 * Recursively list `.md` files under `dir`. Any dot-prefixed path segment below
 * `dir` (`.archive`, a nested `.qe`, `.git`, a stray `.learning`, …) is skipped:
 * those are not execution-document locations and must not pollute the MOC.
 */
function listMarkdown(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const full = join(entry.parentPath, entry.name);
    const belowRoot = relative(dir, full).split(sep).slice(0, -1);
    if (belowRoot.some(seg => seg.startsWith('.'))) continue;
    out.push(full);
  }
  return out;
}

/**
 * List every candidate execution document (absolute path + repo-relative path)
 * under the active `.qe` lifecycle directories. The lint and the rebuild writer
 * share this so they agree on exactly which files are in scope — one walks them
 * to validate, the other to render.
 *
 * @returns {{ full: string, rel: string }[]}
 */
export function listExecutionDocFiles(projectRoot) {
  const qeDir = join(projectRoot, '.qe');
  const files = [];
  for (const root of SCAN_ROOTS) {
    for (const full of listMarkdown(join(qeDir, root))) {
      files.push({ full, rel: relative(projectRoot, full).split(sep).join('/') });
    }
  }
  files.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return files;
}

/**
 * Scan the active execution-document directories under `projectRoot/.qe` and
 * return one entry per document. Shared by the rebuild writer and the lint so
 * both agree on exactly which documents belong in the index.
 *
 * @returns {{ rel: string, kind: string, uuid: string, title: string, status: string }[]}
 */
export function scanDocs(projectRoot) {
  const entries = [];
  for (const { full, rel } of listExecutionDocFiles(projectRoot)) {
    let text = '';
    try {
      text = readFileSync(full, 'utf8');
    } catch {
      continue;
    }
    const fm = extractDocFrontmatter(text);
    const metadata = fm.state === 'valid' ? fm.metadata : null;
    const name = basename(full);
    const kindRaw = metadata && KINDS.includes(metadata.kind) ? metadata.kind : inferKindFromName(name);
    entries.push({
      rel,
      kind: kindRaw,
      uuid: deriveUuid(metadata, name),
      title: deriveTitle(text),
      status: deriveStatus(metadata, rel),
    });
  }
  entries.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return entries;
}

/** Render a single `- [[path]] — title (status)` line. */
function renderLine(entry) {
  const suffix = [entry.title, entry.status ? `(${entry.status})` : '']
    .filter(Boolean)
    .join(' ')
    .trim();
  return suffix ? `- [[${entry.rel}]] — ${suffix}` : `- [[${entry.rel}]]`;
}

/** Render one kind section, sharding by uuid first-hex only past the token limit. */
function renderSection(kind, kindEntries) {
  const lines = [`## ${kind}`, ''];
  if (kindEntries.length === 0) {
    lines.push('_none_', '');
    return lines.join('\n');
  }
  const body = kindEntries.map(renderLine).join('\n');
  if (estimateTokens(body) <= SHARD_TOKEN_LIMIT) {
    lines.push(body, '');
    return lines.join('\n');
  }
  // Past threshold: shard this section by uuid first-hex; non-hex ids to `-misc`.
  const shards = new Map();
  for (const entry of kindEntries) {
    const key = shardKey(entry.uuid);
    if (!shards.has(key)) shards.set(key, []);
    shards.get(key).push(entry);
  }
  for (const key of [...shards.keys()].sort()) {
    lines.push(`### ${kind} · ${key}`, '', shards.get(key).map(renderLine).join('\n'), '');
  }
  return lines.join('\n');
}

/**
 * Compute the full `.qe/index.md` content for the current directory state.
 * Deterministic: identical directory state always yields identical output, so
 * the lint can recompute and compare byte-for-byte.
 */
export function computeIndex(projectRoot) {
  const entries = scanDocs(projectRoot);
  const byKind = new Map(KINDS.map(k => [k, []]));
  for (const entry of entries) {
    if (!byKind.has(entry.kind)) byKind.set(entry.kind, []);
    byKind.get(entry.kind).push(entry);
  }
  const sections = KINDS.map(kind => renderSection(kind, byKind.get(kind) || []));
  return [
    '# QE Execution Index',
    GENERATED_MARKER,
    '',
    `> Derived Map-of-Content over active execution documents. Rebuilt by`,
    `> \`scripts/lib/doc-index.mjs\`; \`.qe/.archive/**\` is excluded. See`,
    `> \`core/DOC_CONVENTIONS.md\`.`,
    '',
    ...sections,
  ].join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

/**
 * Rebuild `.qe/index.md` atomically (temp write + rename). Returns the absolute
 * index path. Callers invoke this ONCE after a document is created or moved —
 * never as an append.
 */
export function rebuildIndex(projectRoot) {
  const content = computeIndex(projectRoot);
  const indexPath = join(projectRoot, '.qe', 'index.md');
  const tmpPath = join(projectRoot, '.qe', `.index.md.${process.pid}.tmp`);
  writeFileSync(tmpPath, content, 'utf8');
  renameSync(tmpPath, indexPath);
  return indexPath;
}

// CLI: `node scripts/lib/doc-index.mjs [projectRoot]` rebuilds the index.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = process.argv[2] || process.cwd();
  const written = rebuildIndex(root);
  console.log(`doc-index: rebuilt ${relative(root, written) || written}`);
}
