#!/bin/bash

# Qcron Daemon Engine
# Usage: ./qcron-daemon.sh [start|stop|list] [job_id] [interval] [mission]

ACTION=$1
JOB_ID=$2
INTERVAL=$3
MISSION=$4

QE_LOG_DIR=".qe/logs/qcron"
JOBS_DIR="scripts/qcron-jobs"
mkdir -p "$QE_LOG_DIR" "$JOBS_DIR"

# Resolve the claude CLI once, at launch, to an absolute path. A detached tmux
# session does not inherit the interactive shell's PATH reliably (claude often
# lives in ~/.local/bin), so a bare `claude` inside the loop can fail to launch.
CLAUDE_BIN="$(command -v claude)"

# Headless + non-interactive flags. THIS IS THE FIX: the old daemon ran
# `claude "$MISSION"` with no `-p`, which in a TTY-less tmux pane starts an
# interactive REPL and blocks forever — the mission never runs and the loop
# never sleeps. `-p/--print` runs headless and exits; `--dangerously-skip-
# permissions` stops the unattended run from stalling on a permission prompt
# it has no TTY to answer. Safety must therefore live in the MISSION prompt
# (scope it; say "do not modify files" for read-only checks).
CLAUDE_FLAGS="-p --dangerously-skip-permissions"

case $ACTION in
  start)
    SESSION_NAME="qcron-$JOB_ID"
    LOG_FILE="$QE_LOG_DIR/job-$JOB_ID.log"
    HEARTBEAT_FILE="$QE_LOG_DIR/heartbeat-$JOB_ID"
    JOB_SCRIPT="$JOBS_DIR/job-$JOB_ID.sh"
    MISSION_FILE="$JOBS_DIR/job-$JOB_ID.mission"

    if [ -z "$CLAUDE_BIN" ]; then
      echo "Qcron: 'claude' CLI not found on PATH — cannot start job $JOB_ID." >&2
      exit 1
    fi

    # 기존 세션이 있으면 종료
    tmux kill-session -t "$SESSION_NAME" 2>/dev/null

    # Mission goes to its own file so arbitrary quotes/$ in the prompt cannot
    # break the generated job script. Written owner-only (umask 077 + chmod 600)
    # so a mission that ever references a secret is not world-readable.
    ( umask 077; printf '%s' "$MISSION" > "$MISSION_FILE" )
    chmod 600 "$MISSION_FILE" 2>/dev/null

    # Generate a dedicated job script (per the Qcron skill design) instead of
    # inlining the loop into the tmux command — this gives correct per-cycle
    # timestamps (evaluated at run time, not frozen at launch) and avoids
    # nested-quote breakage.
    cat > "$JOB_SCRIPT" <<JOBEOF
#!/bin/bash
# Auto-generated by qcron-daemon.sh for Qcron job $JOB_ID. Regenerated on each start.
LOG_FILE="$LOG_FILE"
HEARTBEAT_FILE="$HEARTBEAT_FILE"
MISSION_FILE="$MISSION_FILE"
echo "[\$(date)] Qcron Job $JOB_ID started" >> "\$LOG_FILE"
while true; do
  echo "[\$(date)] Running mission" >> "\$LOG_FILE"
  "$CLAUDE_BIN" $CLAUDE_FLAGS "\$(cat "\$MISSION_FILE")" >> "\$LOG_FILE" 2>&1 \
    || echo "[\$(date)] mission exited non-zero (\$?)" >> "\$LOG_FILE"
  date +%s > "\$HEARTBEAT_FILE"
  echo "[\$(date)] Cycle finished. Sleeping ${INTERVAL}s." >> "\$LOG_FILE"
  sleep $INTERVAL
done
JOBEOF
    chmod 700 "$JOB_SCRIPT"

    # 새로운 백그라운드 세션 생성 (-d: detached)
    tmux new-session -d -s "$SESSION_NAME" "bash '$JOB_SCRIPT'"
    echo "Qcron Job $JOB_ID started in background tmux session: $SESSION_NAME (script: $JOB_SCRIPT)"
    ;;

  stop)
    SESSION_NAME="qcron-$JOB_ID"
    tmux kill-session -t "$SESSION_NAME" 2>/dev/null
    rm -f "$JOBS_DIR/job-$JOB_ID.sh" "$JOBS_DIR/job-$JOB_ID.mission"
    echo "Qcron Job $JOB_ID stopped."
    ;;

  list)
    echo "--- Active Qcron Jobs (tmux sessions) ---"
    tmux ls 2>/dev/null | grep "qcron-" || echo "(none)"
    ;;

  *)
    echo "Usage: $0 [start|stop|list] [job_id] [interval] [mission]"
    ;;
esac
